name: "Build kernels"

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    runs-on: ubuntu-latest
    env:
      kernelDir: "build_dir"
      OUT_DIR: "out"

    steps:
      - name: "üßπ Maximize Build Space"
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          temp-reserve-mb: 100
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: "üòÑ Checkout"
        uses: actions/checkout@v4

      - name: "‚≠ê Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev python3 \
          python-is-python3 libarchive-tools jq device-tree-compiler libelf-dev lz4

      - name: "üåü Clone kernel source"
        run: |
          mkdir -p ${{ env.kernelDir }}
          git clone --depth=1 https://github.com/kawaldhanju33062-tech/SM-M146B-Kernel-Source -b main ${{ env.kernelDir }}/kernel_src

      - name: "üí´ Get Toolchain (Proton-Clang)"
        run: |
          mkdir -p ${{ env.kernelDir }}/toolchain
          cd ${{ env.kernelDir }}/toolchain
          # Using Proton-Clang: highly compatible with Exynos and a direct download link
          wget https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz --strip-components=1
          rm clang.tar.gz
          chmod -R +x bin/

      - name: "üëç Make defconfig"
        working-directory: ./${{ env.kernelDir }}/kernel_src
        run: |
          TC_PATH=$(readlink -f ../toolchain/bin)
          export PATH="$TC_PATH:$PATH"
          make O=../${{ env.OUT_DIR }} ARCH=arm64 \
          CC=clang \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
          LLVM=1 LLVM_IAS=1 \
          s5e8535-m14xnsxx_defconfig

      - name: "üé∂ Build kernel"
        working-directory: ./${{ env.kernelDir }}/kernel_src
        run: |
          TC_PATH=$(readlink -f ../toolchain/bin)
          export PATH="$TC_PATH:$PATH"
          make -j$(nproc --all) O=../${{ env.OUT_DIR }} ARCH=arm64 \
          CC=clang \
          AR=llvm-ar \
          NM=llvm-nm \
          OBJCOPY=llvm-objcopy \
          OBJDUMP=llvm-objdump \
          STRIP=llvm-strip \
          LD=ld.lld \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
          LLVM=1 LLVM_IAS=1

      - name: "üì¶ Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-M146B-${{ github.run_id }}
          path: |
            ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/arm64/boot/Image*
            ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/arm64/boot/*.dtb
            ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/arm64/boot/dtbo.img
          if-no-files-found: warn
          
